#
# # version: '3'

# OLD CONFIGURATION, USE TO AVOID CONFLICT WITH COMPILER ERRORS SHARING NODE_MODULES VOLUME
# services:
#   app:
#     build: .
#     command: ./.docker/start.sh
#     ports:
#       - 3000:3000
#     volumes:
#       - .:/home/node/app
#       - node_modules:/home/node/app/node_modules

# volumes:
#   node_modules:

# version: '3'

services:
  app:
    build: .
    command: ./.docker/start.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      filebeat_collector: true

  db:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      - MYSQL_DATABASE=micro_videos
      - MYSQL_ROOT_PASSWORD=root
    # volumes:
    #   - ./.docker/mysql:/docker-entrypoint-initdb.d
    tmpfs:
      - /var/lib/mysql
    security_opt:
      - seccomp:unconfined

volumes:
  node_modules:

